"""MLX implementation skeleton for vit + trocr.

This file is auto-generated by scripts/convert_to_mlx.py. The weights in
weights.safetensors next to this file have already been renamed to match
the module hierarchy below — fill in the forward-pass code and load them
with `mlx.utils.tree_unflatten(safetensors.load(...))`.

See MLX.md in the repo root for the full porting guide.
"""
import mlx.core as mx
import mlx.nn as nn

# --- inferred from HF config ---------------------------------------------
ENC_HIDDEN = 768
ENC_LAYERS = 12
ENC_HEADS = 12
ENC_INTERMEDIATE = 3072
ENC_PATCH = 16
ENC_IMAGE_SIZE = 448
ENC_CHANNELS = 1

DEC_HIDDEN = 1024
DEC_LAYERS = 12
DEC_HEADS = 16
DEC_INTERMEDIATE = 4096
DEC_VOCAB = 15000
DEC_MAX_POS = 1024


class ViTBlock(nn.Module):
    """Self-attention + MLP, pre-norm. Matches the renamed weights."""
    def __init__(self):
        super().__init__()
        self.norm1 = nn.LayerNorm(ENC_HIDDEN)
        self.attn_q_proj = nn.Linear(ENC_HIDDEN, ENC_HIDDEN)
        self.attn_k_proj = nn.Linear(ENC_HIDDEN, ENC_HIDDEN)
        self.attn_v_proj = nn.Linear(ENC_HIDDEN, ENC_HIDDEN)
        self.attn_out_proj = nn.Linear(ENC_HIDDEN, ENC_HIDDEN)
        self.norm2 = nn.LayerNorm(ENC_HIDDEN)
        self.mlp_fc1 = nn.Linear(ENC_HIDDEN, ENC_INTERMEDIATE)
        self.mlp_fc2 = nn.Linear(ENC_INTERMEDIATE, ENC_HIDDEN)

    def __call__(self, x):
        # TODO(@maintainer): implement self-attention + GELU MLP, residual
        raise NotImplementedError("fill in ViTBlock.__call__ — see MLX.md")


class ViTEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        # patch projection: conv1d-as-linear over flattened patches
        self.patch_embed_proj = nn.Linear(
            ENC_CHANNELS * ENC_PATCH * ENC_PATCH, ENC_HIDDEN
        )
        self.cls_token = mx.zeros((1, 1, ENC_HIDDEN))
        n_patches = (ENC_IMAGE_SIZE // ENC_PATCH) ** 2 + 1
        self.pos_embed = mx.zeros((1, n_patches, ENC_HIDDEN))
        self.layers = [ViTBlock() for _ in range(ENC_LAYERS)]
        self.norm = nn.LayerNorm(ENC_HIDDEN)

    def __call__(self, pixel_values):
        # TODO: patchify -> linear -> add cls + pos -> layers -> norm
        raise NotImplementedError("fill in ViTEncoder.__call__ — see MLX.md")


class TrOCRBlock(nn.Module):
    def __init__(self):
        super().__init__()
        self.self_attn_q_proj = nn.Linear(DEC_HIDDEN, DEC_HIDDEN)
        self.self_attn_k_proj = nn.Linear(DEC_HIDDEN, DEC_HIDDEN)
        self.self_attn_v_proj = nn.Linear(DEC_HIDDEN, DEC_HIDDEN)
        self.self_attn_out_proj = nn.Linear(DEC_HIDDEN, DEC_HIDDEN)
        self.self_attn_norm = nn.LayerNorm(DEC_HIDDEN)
        self.cross_attn_q_proj = nn.Linear(DEC_HIDDEN, DEC_HIDDEN)
        self.cross_attn_k_proj = nn.Linear(ENC_HIDDEN, DEC_HIDDEN)
        self.cross_attn_v_proj = nn.Linear(ENC_HIDDEN, DEC_HIDDEN)
        self.cross_attn_out_proj = nn.Linear(DEC_HIDDEN, DEC_HIDDEN)
        self.cross_attn_norm = nn.LayerNorm(DEC_HIDDEN)
        self.mlp_fc1 = nn.Linear(DEC_HIDDEN, DEC_INTERMEDIATE)
        self.mlp_fc2 = nn.Linear(DEC_INTERMEDIATE, DEC_HIDDEN)
        self.final_norm = nn.LayerNorm(DEC_HIDDEN)

    def __call__(self, x, encoder_h, self_mask=None, kv_cache=None):
        raise NotImplementedError("fill in TrOCRBlock.__call__ — see MLX.md")


class TrOCRDecoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed_tokens = nn.Embedding(DEC_VOCAB, DEC_HIDDEN)
        self.embed_positions = nn.Embedding(DEC_MAX_POS, DEC_HIDDEN)
        self.embed_norm = nn.LayerNorm(DEC_HIDDEN)
        self.layers = [TrOCRBlock() for _ in range(DEC_LAYERS)]
        self.lm_head = nn.Linear(DEC_HIDDEN, DEC_VOCAB, bias=False)

    def __call__(self, input_ids, encoder_h, kv_cache=None):
        raise NotImplementedError("fill in TrOCRDecoder.__call__ — see MLX.md")


class VisionEncoderDecoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.vision = ViTEncoder()
        self.decoder = TrOCRDecoder()

    def encode(self, pixel_values):
        return self.vision(pixel_values)

    def generate(self, pixel_values, *, max_new_tokens=256, bos=0, eos=2):
        raise NotImplementedError("fill in autoregressive generate loop")
